### ISSUE TITLE
Unable to specify relationships while creating/updating a resource

### ISSUE THREAD

**Issue by ngseer** [DeanWay/pydantic-jsonapi#14]
**Describe the bug**
`relationships` clause is not allowed in request data model though it's allowed by [the spec](https://jsonapi.org/format/#crud-creating).

**To Reproduce**
1. Create a new `JsonApiRequest` model.
2. See there's no ability to add relationships to it.

**Expected behavior**
Requests like this should be allowed (an example from the spec):
```
POST /photos HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": {
    "type": "photos",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },
    "relationships": {
      "photographer": {
        "data": { "type": "people", "id": "9" }
      }
    }
  }
}
```

**Comment by DeanWay** [comment]
fixed in 0.10.0, by allowing an optional `relationships` key on request resource objects, consisting of a mapping of strings to objects with a data key as a single resource identifier object (#15)
